### ISSUE TITLE
C4ALL script V 2.0.11.0 - Compressed files (.ZIP)

### ISSUE THREAD

**Issue by HouseVod** [sdckey/C4ALL#12]
We have recently changed to V 2.0.11.0 C4ALL script running on Encase 8.11.

I have noted a case today where media files were not extracted from a .zip file, I have checked another zip file and seems to also be the case with that one as well.

The case was pre-processed using the option to Expand Compound Files, Recovered Folders and File Signature analysis.

In Encase I can click the zip file and see the contents no problem so is not encrypted/password protected.

I have tried the C4ALL script on another machine using the same encase case, on another machine again creating a fresh Encase case all with the same result.

I note from the readme.txt though that it states 'Note that all files must be extracted from a release-archive preserving the relative paths in the process.', I take this to mean pre-process expand compund files?

Please can you advise if there is something I am doing wrong, something we need to change or how we can help you find what is going on?

Many thanks for all your hard work on this project, you are helping countless forensic examiners get the right outcome for so many victims.

**Comment by williams459** [comment]
@HouseVod  - I have been validating this script on Encase v21 and it has been correctly extracting images from Encase mounted compressed files. Depending on the compression method, you can still extract images from an unmounted zip, but you only get a "file offset" as opposed to a path with dates etc. So the fact you got nothing is a bit puzzling.

As I was typing this I ran v2.0.11.0 on Encase v21.2.0.150 using a small test sample set which included a zip, rar, tgz, tar and 7z. I ran case processor with just the mount compressed option and noted all were mounted correctly. Images were extracted out of all the mounted archives and the numbers were correct.

Might be worth checking that you didn't inadvertently run it with a search / ignore tagged / untagged option.
It could be that the newer script isn't functioning quite the same with older versions of Encase as I am aware that Simon had to make some improvements to both script and plugins to improve functionality and success rates. If this is the case you may have to revert to an older script, but you will miss out on some of the new plugins.

**Comment by HouseVod** [comment]
I am just re-testing, it appears to be an issue with using 'current view' or 'tagged items', using either of those and it doesn't seem to drill into any zip files, even if they are specifically tagged, I am testing as I type...

**Comment by HouseVod** [comment]
OK, 

I extracted the two zip files from the case which contain images and videos. I have added a folder with a number of images not in a zipped container, I then zipped all these images into a third zip file so the case now contains 68 images non-compressed. 3 zip files with a mixture of images and videos. I created an Lx01 file from these files so I could pre-process it.

I added the Lx01, verified the file, ran pre-processing for expand compound and file signature analysis.

I tagged the 3 zip files as for review but not the images.

I ran the C4ALL script three times -

First, full case, it found 288 Images and 100 Videos, which is correct.
Second, I opened the image on display and run it using the option of current view, it found 107 images no videos, so it found all the normal/non-compressed files.
Third I ran it again selecting just the tagged items (the 3 zip files) and it found nothing.

I tried this with a different encase file on another computer and got the same results.

It appears that if you choose current view or tagged items, even if you are tagging the zip files themselves it does not extract media from within zip files (only tested zip files, maybe others).

**Comment by sdckey** [comment]
Many thanks for your feedback. It is much appreciated.

The behaviour described by @HouseVod is as expected. EnCase works the same way. If it didn't, you would never be able to process mounted compound files without processing their contents as well.

**Comment by williams459** [comment]
Can you confirm if you are working off L01 or E01 files. I haven't fully checked, but I think C4All doesn't correctly see logical evidence files. I can't say for certain as I rarely use them, but I am sure in the early days, success was limited

**Comment by HouseVod** [comment]
@sdckey 

Just to clarify,

We have some cases where there is a lot of storage and running C4ALL over the entire case is either causing crashes or has time related issues (as was the case in this one).

As a result we have on occasion opened one of the drives and run the script using current view expecting it fully process the drive, including any compressed files, Once complete we open the next drive and repeat the process. Are you saying that using current view will not fully process the evidence file?

This seems to be an issue to me as it is not fully processing the evidence file, if that is the case there needs to be a warning that this view will not process zip files? Is it just zip files or is it any compressed files? Any other media that wont be processed?

Many thanks,

**Comment by HouseVod** [comment]
> Can you confirm if you are working off L01 or E01 files. I haven't fully checked, but I think C4All doesn't correctly see logical evidence files. I can't say for certain as I rarely use them, but I am sure in the early days, success was limited

We normally image our evidence as an E01, I created an Lx01 during my test simply as I dragged and dropped the files into a blank case and needed to create an image file of some form so I could pre-process the file and expand compound files, trying to keep as close to our normal process as possible to try and work out what is going on.

**Comment by sdckey** [comment]
@HouseVod 

The **Search Current View** option does just that - it searches the entries in the current view. If the contents of a mounted compound file aren't in the current view, they won't be searched. 

The same applies to the **Search All Tagged Files** option. For the entries in a mounted compound file to the processed, they must be tagged in their own right.

These are basic iteration options inherited by many scripts. They have worked the same since EnCase 7 was released.

**Comment by HouseVod** [comment]
I will need to brief this out so I need to fully understand exactly what is missed under which circumstances.

If you process the entire case ie all added images using ‘Search All Files’, it will examine all data including compressed folders and any files recovered during the pre-processing for deleted folders, file carver etc.

If I open one of the E01’s for a USB stick, Hard Drive etc and use the current view it will not process the contents of any archive files (.zip, .rar etc). Will it process any files recovered through processing options such as file carver, recover folders? Need to clarify as as far as my understanding went with this is that if the zip file (root file, not expanded files) is in the current view it would be fully processed? Just need to fully understand what isn’t being processed when this option is chosen.

If I run it using all tagged items it will only process the contents of a zip file IF I have gone into the zip file and manually tagged all the contents?

**Comment by williams459** [comment]
Sorry, I misread the original post mentioning the current view option.

In cases where I only have one piece of evidence. I use the search all files option. I don't run C4All across multiple evidence files in one hit. I prefer to compartmentalise.

If I have multi-pieces of **unprocessed** evidence and running C4All on 1 at a time, I use the current view.

If I have auto or manually mounted thumbs, VHD and zips etc, then it is down to tagging. I blue check the whole drive and tag all selected (making sure the tag I am going to use is set to 0). I then click  - view - artefacts - select all the mounted files - select 'open' - In the new pane view blue check and tag checked images / files I want added to the carve. 

I then remove the tags from the master zip, thumb, VHD etc so that they don't get processed as raw data. I do the same for any garbage files that I want to skip eg $bitmap, anything under X number of kbs etc. I then run against tagged files. You could do the opposite and tag what you want excluded, but the method works for me!


OK, so for anyone else reading, the 4 options are:

**Search all files** - I use this when I only have 1 piece of evidence attached to the case AND I want to extract the entire drive. This option (needs confirmation) will auto-exclude $bitmap and zero byte files.

**Search tagged** - self explanatory - if the file aint tagged, it is ignored. This will also search tagged files in other attached evidence whether in the current view or not. One issue you can have here is if you had a tagged files on a piece of evidence that was removed before the files could be untagged. Encase will still show tagged files with a value, even though the evidence is no longer present. I am not quite sure how C4All will handle them when it comes to an absolute path and specific e01 files. I am guessing it will look for something and move on when not found, but don't take my word for that. If you are adding and removing live drives, then it has more serious implications. Drive 3 can be replaced by another drive also numbered 3 in Encase and in this case, there will be data present, but the wrong drive. Best and safest practice - check the tag you are going to use is 0 value - or create a new tag and name it accordingly.

**Exclude tagged** - opposite to above with similar tagging issues if not careful.

**Search current view** - Used when you have more than 1 piece of evidence attached to the case, but only want to search those you have open in the view pane. If you can't see it in the view pane, it will be ignored - no drilling down through hyperlinks. If you can't see it when green plated, you won't get it carved. You may still get some images from the unmounted zip, but this depends on compression method.

**Comment by HouseVod** [comment]
I have spoken to colleagues in the office who have been doing this job longer than me for a sanity check and confirm the current understanding within the office. 

They were unaware that if a compressed file is in the current view that the script using current view would not extract media from within the compressed file. Our understanding was that if the file was on view it would be fully explored for media. 

As per your example, computers are getting bigger and running a script over lots of large hard drives presents a significant amount of time to process. We therefore, as you do, process one drive at a time to essentially compartmentalise the case in case of network/machine failure, the process can be re-started on one drive rather than the whole case, thus reducing ‘lost’ work. We don’t do it often this way, depends on the case.

Is there a quick/easy way to open all files that would have been skipped (Ie compressed files) and bookmarking all contents to process what has been missed using the tagged items option?

We can not find any references in the documentation that compressed files will not be examined, can there be a warning on the script or the documentation to promote a better understanding of the script.

Thank you,

**Comment by sdckey** [comment]
@williams459 - Many thanks for jumping in and adding the additional clarification.

> This option (needs confirmation) will auto-exclude $bitmap and zero byte files.

Yes, zero-byte files are excluded, not that it would make much difference if they weren't - they would take next to no time to search.

With regards to `$Bitmap`, perhaps you mean `$BadClus·$Bad`? If so, from what I can see, that file-stream isn't excluded specifically. However, unless there are bad clusters on the volume, it's unlikely to make much difference because it will be 100% sparse. In other words, the null bytes it contains won't actually exist. This can be confirmed by looking at the file's extents in the **View** pane. Consequently, if you perform a raw keyword search of `$BadClus·$Bad`, it should finish almost immediately.

**Comment by sdckey** [comment]
I have added a note to the [README](https://github.com/sdckey/C4ALL/blob/master/README.md) file as well as an additional compound-file help button on the main dialog.

**Comment by sdckey** [comment]
@williams459 

> The reason I thought they were now excluded was the lines in AnalysisController.Enscript where there are entries to exclude BadClus, Mounted, Empty and Overwritten. That being said, I am no coder and don't know diddly about Enscripts, so I could be reading the script incorrectly.

Sorry Tim - You are entirely correct. I somehow managed to miss that code. I've run it through the debugger and it's definitely hitting on [that line](https://github.com/sdckey/C4ALL/blob/20e52956e2e6be58200ecea862460027528103f8/Engine/Core%20Files/Controllers/AnalysisController.EnScript#L160).
